import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google';
import './globals.css'
import HeaderSSR from './ssr/header'
import Header from './header'
const openSans = Open_Sans({
  subsets: ['latin'],
  // weight: ['300','400', '500', '600', '700'],
  // style: ['normal'],
  variable: '--open-sans',
});


console.log(openSans)
export const metadata: Metadata = {
  title: 'Tailwind Next',
  description: 'Generated by create next app with Tailwind',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>

      </head>
      <body className={`bg-zinc-700 md:mx-2 mx-5 ${ openSans.className}`}>
        {/* <Context> */}
          <Header></Header>
          <HeaderSSR></HeaderSSR>
          {children}
        {/* </Context> */}
     
      </body>
    </html>
  )
}
