import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import HeaderSSR from './ssr/header'
import Header from './header'
// import Context from "../../context/context"


export const metadata: Metadata = {
  title: 'Tailwind Next',
  description: 'Generated by create next app with Tailwind',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className='bg-zinc-700 md:mx-2 mx-5'>
        {/* <Context> */}
          <Header></Header>
          <HeaderSSR></HeaderSSR>
          {children}
        {/* </Context> */}
     
      </body>
    </html>
  )
}
